workflows:
  flutter-test:
    name: Flutter Test & Coverage
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
        - pattern: develop
          include: true
    environment:
      flutter: stable
      groups:
        - my_env_variables
    scripts:
    - name: Increase Git buffer size
      script: |
        git config --global http.postBuffer 524288000
        git config --global core.compression 0
    scripts:
      - name: Prebuild Script
        script: |
          flutter clean
          flutter pub get
          echo "AUTH_KEY=$AUTH_KEY" > assets/.env
          echo "USER_KEY=$USER_KEY" >> assets/.env
          echo "SERVICE_KEY=$SERVICE_KEY" >> assets/.env
          echo "HOME_CLEAN_URL=$HOME_CLEAN_URL" >> assets/.env
          echo "VIN_WALLET_URL=$VIN_WALLET_URL" >> assets/.env
      - name: Run tests with coverage
        script: |
          flutter test --coverage
          genhtml coverage/lcov.info -o coverage/html
    artifacts:
      - coverage/html/**
    publishing:
      email:
        recipients:
          - "9.10nguyenhuubao@gmail.com"
