workflows:
  flutter-test:
    name: Flutter Test & Coverage
    environment:
      flutter: stable
      groups:
        - my_env_variables
    scripts:
      - name: Prebuild Script
        script: |
          flutter clean
          flutter pub get
          echo "AUTH_KEY=$AUTH_KEY" > assets/.env
          echo "USER_KEY=$USER_KEY" >> assets/.env
          echo "SERVICE_KEY=$SERVICE_KEY" >> assets/.env
          echo "HOME_CLEAN_URL=$HOME_CLEAN_URL" >> assets/.env
          echo "VIN_WALLET_URL=$VIN_WALLET_URL" >> assets/.env

      - name: Run tests with coverage
        script: |
          flutter test --coverage

      - name: Generate coverage report
        script: |
          flutter pub global activate flutter_lcov
          flutter_lcov -i coverage/lcov.info -o coverage/html

      - name: Upload coverage to Codecov
        script: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t YOUR_CODECOV_TOKEN || echo "Codecov upload failed"

    artifacts:
      - coverage/html/**

    publishing:
      email:
        recipients:
          - "9.10nguyenhuubao@gmail.com"

      
