name: home_clean
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.0.0
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  device_info_plus: ^11.1.1
  #$google_sign_in: ^6.2.2
  equatable: ^2.0.5
  intl: ^0.19.0
  timeline_tile: ^2.0.0
  awesome_snackbar_content: ^0.1.4
  google_fonts: ^6.2.1
  dio: ^5.7.0
#  firebase_auth: ^5.3.1
  panara_dialogs: ^0.1.5
  connectivity_plus: ^6.1.0
  shared_preferences: ^2.5.2
  carousel_slider: ^5.0.0
  toastification: ^3.0.2
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  sqflite: ^2.4.1
  get: ^4.6.6
  get_it: ^8.0.3
  url_launcher: ^6.3.1
  lottie: ^3.3.0
  curved_navigation_bar: ^1.0.6
  shimmer: ^3.0.0
  diacritic: ^0.1.6
  easy_date_timeline: ^2.0.6
  wheel_picker: ^0.2.1
  geolocator: ^13.0.2
  signalr_netcore: ^1.4.0
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^19.1.0
  flutter_map: ^8.0.0
  location: ^8.0.0
  latlong2: ^0.9.1
  flutter_map_animations: ^0.9.0
  flutter_secure_storage: ^9.2.4
  test: any
  dartz: ^0.10.1
  webview_flutter: ^4.10.0
  flutter_dotenv: ^5.2.1
  permission_handler: ^12.0.0+1
  collection: ^1.19.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  mockito: ^5.4.5
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
